apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-explorer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: blockchain-explorer-app
  template:
    metadata:
      labels:
        name: blockchain-explorer-app
    spec:
      volumes:
        - name: ndafiles
          persistentVolumeClaim:
            claimName: nda-pvc
      containers:
        - name: explorer
          image: hyperledger/explorer:latest
          command: ["sh", "-c", "/fabric/config/explorer/app/run.sh"]
          env:
            - name: DATABASE_HOST
              value: blockchain-explorer-db
            - name: DATABASE_PORT
              value: "30432"
            - name: DATABASE_NAME
              value: fabricexplorer
            - name: DATABASE_USERNAME
              value: hppoc
            - name: DATABASE_PASSWORD
              value: password
          volumeMounts:
            - mountPath: /fabric
              name: ndafiles
