apiVersion: apps/v1
kind: Deployment
metadata:
  name: nda-backend-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nda-backend-mongodb
  template:
    metadata:
      labels:
        name: nda-backend-mongodb
    spec:
      containers:
        - name: nda-backend-mongodb
          image: mongo
          ports:
            - name: mongo
              containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: nda-backend-mongodb
spec:
  selector:
    name: nda-backend-mongodb
  type: NodePort
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30717
