apiVersion: apps/v1
kind: Deployment
metadata:
  name: nda-backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nda-backend-api
  template:
    metadata:
      labels:
        name: nda-backend-api
    spec:
      containers:
        - name: nda-backend-api
          image: sarathkaleswaram/nda-backend:1.0.1
          env:
            - name: MONGO_URL
              value: nda-backend-mongodb:27017
          ports:
            - name: api
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nda-backend-api
spec:
  selector:
    name: nda-backend-api
  type: NodePort
  ports:
    - name: api
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
