apiVersion: apps/v1
kind: Deployment
metadata:
  name: nda-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nda-cli
  template:
    metadata:
      labels:
        name: nda-cli
    spec:
      volumes:
        - name: ndafiles
          persistentVolumeClaim:
            claimName: nda-pvc
        - name: run
          hostPath:
            path: /var/run
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
      containers:
        - name: nda-cli
          image: hyperledger/fabric-tools:1.4.4
          env:
            - name: GOPATH
              value: /opt/gopath
            # - name: CORE_VM_ENDPOINT
            #   value: unix:///host/var/run/docker.sock
            - name: CORE_VM_ENDPOINT
              value: tcp://docker:2375
            - name: CORE_PEER_ID
              value: nda-cli
            - name: FABRIC_LOGGING_SPEC
              value: INFO
            - name: CORE_PEER_ADDRESS
              value: nda-peer0-org1:30751
            - name: CORE_PEER_LOCALMSPID
              value: Org1MSP
            - name: CORE_PEER_TLS_ENABLED
              value: "false"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/peers/peer0.org1/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/peers/peer0.org1/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/peers/peer0.org1/tls/ca.crt
            - name: CORE_PEER_MSPCONFIGPATH
              value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
          volumeMounts:
            - mountPath: /opt/gopath/src/github.com/chaincode
              name: ndafiles
              subPath: chaincode
            - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
              name: ndafiles
              subPath: crypto-config
            - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
              name: ndafiles
              subPath: channel-artifacts
            - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
              name: ndafiles
              subPath: scripts
            - mountPath: /host/var/run/docker.sock
              name: dockersocket
