apiVersion: apps/v1
kind: Deployment
metadata:
  name: nda-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nda-ca
  template:
    metadata:
      labels:
        app: nda-ca
    spec:
      volumes:
        - name: ndafiles
          persistentVolumeClaim:
            claimName: nda-pvc
      containers:
        - name: nda-ca
          image: hyperledger/fabric-ca:1.4.4
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: FABRIC_CA_SERVER_CA_NAME
              value: ca-org1
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "false"
            - name: FABRIC_CA_SERVER_TLS_CERTFILE
              value: /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
            - name: FABRIC_CA_SERVER_TLS_KEYFILE
              value: /etc/hyperledger/fabric-ca-server-config/622360c9dc5c9e83aec7466dc809b6d10cb9b5efaf84a1bcfb857f5b45a6954a_sk
          ports:
            - containerPort: 7054
          command: ["sh"]
          args:
            [
              "-c",
              " fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/622360c9dc5c9e83aec7466dc809b6d10cb9b5efaf84a1bcfb857f5b45a6954a_sk -b admin:adminpw -d",
            ]
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric-ca-server-config
              name: ndafiles
              subPath: crypto-config/peerOrganizations/org1.example.com/ca/

---
apiVersion: v1
kind: Service
metadata:
  name: nda-ca
spec:
  selector:
    app: nda-ca
  type: NodePort
  ports:
    - name: endpoint
      protocol: TCP
      port: 30754
      targetPort: 7054
      nodePort: 30754
