apiVersion: apps/v1
kind: Deployment
metadata:
  name: nda-explorer-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nda-explorer-db
  template:
    metadata:
      labels:
        name: nda-explorer-db
    spec:
      volumes:
        - name: ndafiles
          persistentVolumeClaim:
            claimName: nda-pvc
      containers:
        - name: nda-explorer-db
          image: hyperledger/explorer-db:latest
          env:
            - name: DATABASE_DATABASE
              value: fabricexplorer
            - name: DATABASE_USERNAME
              value: hppoc
            - name: DATABASE_PASSWORD
              value: password
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/createdb.sh
              name: ndafiles
              subPath: explorer/createdb.sh
          ports:
            - name: psql
              containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: nda-explorer-db
spec:
  selector:
    name: nda-explorer-db
  type: NodePort
  ports:
    - name: psql
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432