apiVersion: apps/v1
kind: Deployment
metadata:
  name: nda-orderer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nda-orderer
  template:
    metadata:
      labels:
        name: nda-orderer
    spec:
      volumes:
        - name: ndafiles
          persistentVolumeClaim:
            claimName: nda-pvc
      containers:
        - name: nda-orderer
          image: hyperledger/fabric-orderer:1.4.4
          env:
            - name: FABRIC_LOGGING_SPEC
              value: info
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: 0.0.0.0
            - name: ORDERER_GENERAL_LISTENPORT
              value: "30750"
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: file
            - name: ORDERER_GENERAL_GENESISFILE
              value: /var/hyperledger/orderer/orderer.genesis.block
            - name: ORDERER_GENERAL_LOCALMSPID
              value: OrdererMSP
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: /var/hyperledger/orderer/msp
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "false"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: /var/hyperledger/orderer/tls/server.key
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: /var/hyperledger/orderer/tls/server.crt
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: "[/var/hyperledger/orderer/tls/ca.crt]"
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric
          command: ["orderer"]
          volumeMounts:
            - mountPath: /var/hyperledger/orderer/orderer.genesis.block
              name: ndafiles
              subPath: channel-artifacts/genesis.block
            - mountPath: /var/hyperledger/orderer/msp
              name: ndafiles
              subPath: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp
            - mountPath: /var/hyperledger/orderer/tls
              name: ndafiles
              subPath: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls

---
apiVersion: v1
kind: Service
metadata:
  name: nda-orderer
spec:
  selector:
    name: nda-orderer
  type: NodePort
  ports:
    - name: grpc
      protocol: TCP
      port: 30750
      targetPort: 30750
      nodePort: 30750
