apiVersion: v1
kind: PersistentVolume
metadata:
  name: nda-pv
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem #remove if server ip added
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/share
    server: storage.local.parisi.biz #nfs server ip

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nda-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
