apiVersion: v1
kind: Pod
metadata:
  name: nda-copy-files
  labels:
    app: nda-copy-files
spec:
  volumes:
    - name: ndafiles
      persistentVolumeClaim:
        claimName: nda-pvc
  containers:
    - name: nda-copy-files
      image: hyperledger/fabric-tools:1.4.4
      command: ["sh", "-c", "sleep 48h"]
      env:
        - name: FABRIC_CFG_PATH
          value: /fabric
      volumeMounts:
        - mountPath: /opt/share
          name: ndafiles
