apiVersion: v1
kind: PersistentVolume
metadata:
  name: nda-pv
  labels:
    type: local
    name: ndafiles
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/share
    server: storage.local.parisi.biz
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nda-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
