apiVersion: v1
kind: Pod
metadata:
  name: fabric-tools
spec:
  volumes:
  - name: ndafiles
    persistentVolumeClaim:
      claimName: nda-pvc
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock
  containers:
    - name: fabrictools
      image: hyperledger/fabric-tools:1.4.4
      imagePullPolicy: Always
      command: ["sh", "-c", "sleep 48h"]
      env:
      - name: FABRIC_CFG_PATH
        value: "/fabric"
      volumeMounts:
        - mountPath: /opt/share
          name: ndafiles
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
