apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ca
  template:
    metadata:
      labels:
        app: ca
    spec:
      volumes:
        - name: ndafiles
          persistentVolumeClaim:
            claimName: nda-pvc
      containers:
        - name: ca
          image: hyperledger/fabric-ca:1.4.4
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: FABRIC_CA_SERVER_CA_NAME
              value: ca-org1
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "false"
            - name: FABRIC_CA_SERVER_TLS_CERTFILE
              value: /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
            - name: FABRIC_CA_SERVER_TLS_KEYFILE
              value: /etc/hyperledger/fabric-ca-server-config/6825559c28c2988e0a95cc3e6717cfb95a1667a10a0e3ce37f77240d0ab75c2c_sk
          ports:
            - containerPort: 7054
          command: ["sh"]
          args:
            [
              "-c",
              " fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/6825559c28c2988e0a95cc3e6717cfb95a1667a10a0e3ce37f77240d0ab75c2c_sk -b admin:adminpw -d",
            ]
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric-ca-server-config
              name: ndafiles
              subPath: crypto-config/peerOrganizations/org1.example.com/ca/

---
apiVersion: v1
kind: Service
metadata:
  name: ca
spec:
  selector:
    app: ca
  type: NodePort
  ports:
    - name: endpoint
      protocol: TCP
      port: 30054
      targetPort: 7054
      nodePort: 30054
