apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer1-org1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peer1-org1
  template:
    metadata:
      labels:
        app: peer1-org1
    spec:
      volumes:
        - name: ndafiles
          persistentVolumeClaim:
            claimName: nda-pvc
        - name: run
          hostPath:
            path: /var/run
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
      containers:
        - name: peer1-org1
          image: hyperledger/fabric-peer:1.4.4
          env:
            - name: CORE_VM_ENDPOINT
              value: unix:///host/var/run/docker.sock
            - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
              value: "bridge"
            - name: FABRIC_LOGGING_SPEC
              value: INFO
            - name: CORE_PEER_TLS_ENABLED
              value: "false"
            - name: CORE_PEER_GOSSIP_ORGLEADER
              value: "false"
            - name: CORE_PEER_PROFILE_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /etc/hyperledger/fabric/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /etc/hyperledger/fabric/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /etc/hyperledger/fabric/tls/ca.crt
            - name: CORE_PEER_ID
              value: "peer1-org1"
            - name: CORE_PEER_ADDRESS
              value: "peer1-org1:30210"
            - name: CORE_PEER_LISTENADDRESS
              value: 0.0.0.0:30210
            - name: CORE_PEER_CHAINCODEADDRESS
              value: "peer1-org1:30211"
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: 0.0.0.0:30211
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: "peer1-org1:30210"
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: "peer1-org1:30210"
            - name: CORE_PEER_LOCALMSPID
              value: Org1MSP
            - name: ORDERER_URL
              value: orderer:31010
            - name: CORE_PEER_NETWORKID
              value: nid1
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          command: ["peer"]
          args: ["node", "start"]
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric/msp
              name: ndafiles
              subPath: crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp
            - mountPath: /etc/hyperledger/fabric/tls
              name: ndafiles
              subPath: crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls
            - mountPath: /host/var/run/
              name: run
            - mountPath: /host/var/run/docker.sock
              name: dockersocket

---
apiVersion: v1
kind: Service
metadata:
  name: peer1-org1
spec:
  selector:
    name: peer1-org1
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30210
    targetPort: 30210
    port: 30210
    name: grpc
  - protocol: TCP
    nodePort: 30211
    targetPort: 30211
    port: 30211
    name: events
